channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - ninja
  - protobuf
  - pip:
    - hypothesis
    - future
    - cloudpickle
    - gym
    - gym[accept-rom-license]
    - gym[atari]
    - tqdm
    - pytest
    - pytest-cov
    - pytest-mock
    - expecttest
    - pyyaml
    - scipy
    - hydra-core
    - tensorboard
